--- 
abstract: convert to HTTP::Request object from Apache's access_log record.
author: 
  - Takeshi Miki <miki@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.70
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTTP-Request-FromLog
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  HTTP::Headers: 0
  HTTP::Request: 0
  List::MoreUtils: 0
  Parse::AccessLogEntry: 0
  UNIVERSAL::require: 0
  perl: 5.8.1
version: 0.00001
